apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example

resources:
  - github.com/thestormforge/examples/voting-webapp/application
  - github.com/thestormforge/examples/locust-metrics/locust?ref=package_locust
  - hpa.yaml
  - experiment.yaml
  - prometheus-sa.yaml
  - trialjob_configmap.yaml

configMapGenerator:
- name: locust-load-test
  files:
  - load_test.py

generatorOptions:
  disableNameSuffixHash: true
