apiVersion: v1
kind: ServiceAccount
metadata:
  name: redsky
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nuodb-setup
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redsky-nuodb-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nuodb-setup
subjects:
- kind: ServiceAccount
  name: default
  namespace: nuodb