apiVersion: apps.redskyops.dev/v1alpha1
kind: Application
metadata:
  name: votingapp-sf

resources:
- application

ingress:
  url: "http://35.244.198.192"

parameters:
  containerResources:
    labelSelector: component=voting-service
  replicas:
    labelSelector: component=voting-service


scenarios:
- name: standard
  stormforger:
    testCaseFile: experiment.js
stormForger:
  org: sf_sandbox
  # accessToken:
  #   file: sf-jwt # otherwise jwt from forge config is used


objectives:
- name: p50-latency
  optimize: false
- name: p95-latency
- name: p99-latency
  optimize: false
- name: cost
  requests:
    labels:
      app: voting-app


